"""Dostop do podatkov v PostgreSQL bazi.

Razred Repository na enem mestu zbere SQL-poizvedbe aplikacije. Datoteki
app.py in poznejši servisi zato ne potrebujejo neposrednega dela s psycopg2.
Koda je usklajena s tabelami iz data/create_database.sql.
"""

from dataclasses import dataclass

import psycopg2

# Pika pomeni uvoz iz istega paketa (mape data). Uvoz zato pravilno deluje,
# ko v app.py napišemo: from data.repository import Repository
from . import auth_public as auth
from .models import oseba


# -------------------------------------------------------------------------
# POMOŽNI PODATKOVNI RAZREDI (DTO)
# -------------------------------------------------------------------------

@dataclass
class Sifrant:
    """Ena vrstica preprostega šifranta, npr. kategorija ali pripomoček."""

    id: int
    ime: str


@dataclass
class SestavinaRecepta:
    """Sestavina skupaj s količino in enoto v konkretnem receptu."""

    id: int
    ime: str
    kolicina: str
    enota: str


@dataclass
class SladicaDTO:
    """Podatki o sladici, pripravljeni za prikaz v HTML-predlogi.

    Tabela sladica hrani samo ID-je avtorja, težavnosti in kategorije.
    SQL-poizvedba z JOIN-i doda še njihova berljiva imena.
    """

    id: int
    ime: str
    cas_priprave: int
    postopek: str
    kratek_opis: str
    avtor_id: int
    avtor: str
    tezavnost_id: int
    tezavnost: str
    kategorija_id: int
    kategorija: str


class Repository:
    """Vse poizvedbe za dostop do baze.

    Primer uporabe::

        with Repository() as repo:
            sladice = repo.dobi_vse_sladice()

    Ko se blok with konča, se povezava samodejno zapre.
    """

    # Osnovni SELECT za sladice uporabljamo v več metodah. JOIN poveže
    # tabelo sladica s tabelami oseba, tezavnost in kategorija.
    # Vrstni red stolpcev se mora ujemati z razredom SladicaDTO.
    SQL_SLADICE = """
        SELECT
            s.id,
            s.ime,
            s.cas_priprave,
            s.postopek,
            s.kratek_opis,
            o.id AS avtor_id,
            o.ime || ' ' || o.priimek AS avtor,
            t.id AS tezavnost_id,
            t.tezavnost,
            k.id AS kategorija_id,
            k.ime AS kategorija
        FROM sladica AS s
        JOIN oseba AS o ON o.id = s.avtor
        JOIN tezavnost AS t ON t.id = s.tezavnost
        JOIN kategorija AS k ON k.id = s.kategorija
    """

    def __init__(self):
        """Odpre povezavo s podatki iz auth_public.py."""

        self.conn = psycopg2.connect(
            dbname=auth.db,
            host=auth.host,
            user=auth.user,
            password=auth.password,
            port=auth.port,
        )

    def zapri(self):
        """Zapre povezavo, če je ta še odprta."""

        if self.conn is not None and not self.conn.closed:
            self.conn.close()

    def __enter__(self):
        """Omogoči uporabo with Repository() as repo."""

        return self

    def __exit__(self, exc_type, exc_value, traceback):
        """Ob izhodu iz bloka with vedno zapre povezavo."""

        self.zapri()

    @staticmethod
    def _naslednji_id(cur, tabela: str) -> int:
        """Izračuna naslednji prosti ID v tabeli oseba ali sladica.

        V trenutni SQL-shemi so ID-ji navadni INTEGER in se ne ustvarijo
        samodejno. Zato Repository pred vstavljanjem poišče največji ID in
        mu prišteje 1. Za aplikacijo z veliko sočasnimi uporabniki bi bilo
        bolje uporabiti GENERATED BY DEFAULT AS IDENTITY.
        """

        dovoljene_tabele = {"oseba", "sladica"}
        if tabela not in dovoljene_tabele:
            raise ValueError(f"ID-ja ni dovoljeno ustvariti za tabelo {tabela!r}.")

        # Ime tabele prihaja samo iz kode, ne iz uporabniškega obrazca.
        cur.execute(f"SELECT COALESCE(MAX(id), 0) + 1 FROM {tabela}")
        return cur.fetchone()[0]

    # =====================================================================
    # OSEBE
    # =====================================================================

    def dobi_osebo(self, oseba_id: int) -> oseba | None:
        """Vrne osebo z danim ID-jem ali None, če oseba ne obstaja."""

        # with self.conn predstavlja transakcijo. Ob uspehu se izvede COMMIT,
        # ob napaki pa ROLLBACK. Cursor se po notranjem bloku sam zapre.
        with self.conn:
            with self.conn.cursor() as cur:
                cur.execute(
                    """
                    SELECT id, ime, priimek, elektronski_naslov,
                           uporabnisko_ime, geslo
                    FROM oseba
                    WHERE id = %s
                    """,
                    (oseba_id,),
                )
                vrstica = cur.fetchone()

        if vrstica is None:
            return None

        # Zvezdica razpakira šest vrednosti v konstruktor razreda oseba.
        return oseba(*vrstica)

    def dobi_osebo_po_uporabniskem_imenu(
        self, uporabnisko_ime: str
    ) -> oseba | None:
        """Poišče osebo po uporabniškem imenu; uporabno pri prijavi."""

        with self.conn:
            with self.conn.cursor() as cur:
                cur.execute(
                    """
                    SELECT id, ime, priimek, elektronski_naslov,
                           uporabnisko_ime, geslo
                    FROM oseba
                    WHERE uporabnisko_ime = %s
                    """,
                    (uporabnisko_ime,),
                )
                vrstica = cur.fetchone()

        return None if vrstica is None else oseba(*vrstica)

    def dobi_vse_osebe(self) -> list[oseba]:
        """Vrne vse osebe, urejene po priimku in imenu."""

        with self.conn:
            with self.conn.cursor() as cur:
                cur.execute(
                    """
                    SELECT id, ime, priimek, elektronski_naslov,
                           uporabnisko_ime, geslo
                    FROM oseba
                    ORDER BY priimek, ime
                    """
                )
                vrstice = cur.fetchall()

        return [oseba(*vrstica) for vrstica in vrstice]

    def dodaj_osebo(
        self,
        ime: str,
        priimek: str,
        elektronski_naslov: str,
        uporabnisko_ime: str,
        geslo: str,
    ) -> int:
        """Doda osebo in vrne njen novi ID.

        Repository gesla ne šifrira. Pred klicem mora servis geslo pretvoriti
        v bcrypt zgoščeno vrednost. Če je e-pošta ali uporabniško ime že v
        bazi, PostgreSQL sproži napako in transakcija se razveljavi.
        """

        with self.conn:
            with self.conn.cursor() as cur:
                novi_id = self._naslednji_id(cur, "oseba")
                cur.execute(
                    """
                    INSERT INTO oseba (
                        id, ime, priimek, elektronski_naslov,
                        uporabnisko_ime, geslo
                    )
                    VALUES (%s, %s, %s, %s, %s, %s)
                    """,
                    (
                        novi_id,
                        ime,
                        priimek,
                        elektronski_naslov,
                        uporabnisko_ime,
                        geslo,
                    ),
                )

        return novi_id

    # =====================================================================
    # SLADICE
    # =====================================================================

    @staticmethod
    def _ustvari_sladico_dto(vrstica) -> SladicaDTO:
        """Pretvori eno SQL-vrstico v objekt SladicaDTO."""

        return SladicaDTO(*vrstica)

    def dobi_vse_sladice(self) -> list[SladicaDTO]:
        """Vrne vse sladice z avtorjem, težavnostjo in kategorijo."""

        with self.conn:
            with self.conn.cursor() as cur:
                cur.execute(self.SQL_SLADICE + " ORDER BY s.ime")
                vrstice = cur.fetchall()

        return [self._ustvari_sladico_dto(vrstica) for vrstica in vrstice]

    def dobi_sladico(self, sladica_id: int) -> SladicaDTO | None:
        """Vrne eno sladico ali None, če tak ID ne obstaja."""

        with self.conn:
            with self.conn.cursor() as cur:
                cur.execute(
                    self.SQL_SLADICE + " WHERE s.id = %s",
                    (sladica_id,),
                )
                vrstica = cur.fetchone()

        return None if vrstica is None else self._ustvari_sladico_dto(vrstica)

    def dodaj_sladico(
        self,
        ime: str,
        cas_priprave: int,
        postopek: str,
        kratek_opis: str,
        avtor_id: int,
        tezavnost_id: int,
        kategorija_id: int,
        sestavine: list[tuple[int, str, str]] | None = None,
        pripomocki: list[int] | None = None,
    ) -> int:
        """Doda sladico, sestavine in pripomočke v eni transakciji.

        sestavine so trojice (id_sestavine, kolicina, enota), na primer
        [(1, "200", "g"), (3, "2", "kos")]. Pripomocki so seznam ID-jev.
        Če pade vstavljanje ene povezave, se razveljavi tudi vstavljeni recept.
        """

        sestavine = sestavine or []
        pripomocki = pripomocki or []

        with self.conn:
            with self.conn.cursor() as cur:
                sladica_id = self._naslednji_id(cur, "sladica")
                cur.execute(
                    """
                    INSERT INTO sladica (
                        id, ime, cas_priprave, postopek, kratek_opis,
                        avtor, tezavnost, kategorija
                    )
                    VALUES (%s, %s, %s, %s, %s, %s, %s, %s)
                    """,
                    (
                        sladica_id,
                        ime,
                        cas_priprave,
                        postopek,
                        kratek_opis,
                        avtor_id,
                        tezavnost_id,
                        kategorija_id,
                    ),
                )

                # vsebuje je povezovalna tabela med sladicami in sestavinami.
                for sestavina_id, kolicina, enota in sestavine:
                    cur.execute(
                        """
                        INSERT INTO vsebuje (
                            sladica, sestavina, kolicina_sestavine, enota
                        )
                        VALUES (%s, %s, %s, %s)
                        ON CONFLICT (sladica, sestavina)
                        DO UPDATE SET
                            kolicina_sestavine = EXCLUDED.kolicina_sestavine,
                            enota = EXCLUDED.enota
                        """,
                        (sladica_id, sestavina_id, kolicina, enota),
                    )

                # set odstrani morebitne podvojene ID-je pripomočkov.
                for pripomocek_id in set(pripomocki):
                    cur.execute(
                        """
                        INSERT INTO potrebujes (sladica, pripomocek)
                        VALUES (%s, %s)
                        ON CONFLICT (sladica, pripomocek) DO NOTHING
                        """,
                        (sladica_id, pripomocek_id),
                    )

        return sladica_id

    # =====================================================================
    # ŠIFRANTI: KATEGORIJE, TEŽAVNOSTI, SESTAVINE IN PRIPOMOČKI
    # =====================================================================

    def dobi_kategorije(self) -> list[Sifrant]:
        """Vrne vse kategorije, urejene po imenu."""

        with self.conn:
            with self.conn.cursor() as cur:
                cur.execute("SELECT id, ime FROM kategorija ORDER BY ime")
                vrstice = cur.fetchall()

        return [Sifrant(*vrstica) for vrstica in vrstice]

    def dobi_tezavnosti(self) -> list[Sifrant]:
        """Vrne težavnosti; besedilo stolpca tezavnost postane ime."""

        with self.conn:
            with self.conn.cursor() as cur:
                cur.execute("SELECT id, tezavnost FROM tezavnost ORDER BY id")
                vrstice = cur.fetchall()

        return [Sifrant(*vrstica) for vrstica in vrstice]

    def dobi_vse_sestavine(self) -> list[Sifrant]:
        """Vrne vse sestavine.

        Tabela sestavina v trenutni shemi nima enote. Enota se bere iz
        povezovalne tabele vsebuje pri posameznem receptu.
        """

        with self.conn:
            with self.conn.cursor() as cur:
                cur.execute("SELECT id, ime FROM sestavina ORDER BY ime")
                vrstice = cur.fetchall()

        return [Sifrant(*vrstica) for vrstica in vrstice]

    def dobi_sestavine_sladice(
        self, sladica_id: int
    ) -> list[SestavinaRecepta]:
        """Vrne imena, količine in enote sestavin izbranega recepta."""

        with self.conn:
            with self.conn.cursor() as cur:
                cur.execute(
                    """
                    SELECT se.id, se.ime, v.kolicina_sestavine, v.enota
                    FROM vsebuje AS v
                    JOIN sestavina AS se ON se.id = v.sestavina
                    WHERE v.sladica = %s
                    ORDER BY se.ime
                    """,
                    (sladica_id,),
                )
                vrstice = cur.fetchall()

        return [SestavinaRecepta(*vrstica) for vrstica in vrstice]

    def dobi_vse_pripomocke(self) -> list[Sifrant]:
        """Vrne vse pripomočke, urejene po imenu."""

        with self.conn:
            with self.conn.cursor() as cur:
                cur.execute("SELECT id, ime FROM pripomocek ORDER BY ime")
                vrstice = cur.fetchall()

        return [Sifrant(*vrstica) for vrstica in vrstice]

    def dobi_pripomocke_sladice(self, sladica_id: int) -> list[Sifrant]:
        """Vrne pripomočke, povezane z izbrano sladico."""

        with self.conn:
            with self.conn.cursor() as cur:
                cur.execute(
                    """
                    SELECT p.id, p.ime
                    FROM potrebujes AS po
                    JOIN pripomocek AS p ON p.id = po.pripomocek
                    WHERE po.sladica = %s
                    ORDER BY p.ime
                    """,
                    (sladica_id,),
                )
                vrstice = cur.fetchall()

        return [Sifrant(*vrstica) for vrstica in vrstice]

    # =====================================================================
    # PRILJUBLJENE SLADICE
    # =====================================================================

    def dodaj_med_priljubljene(self, oseba_id: int, sladica_id: int) -> None:
        """Doda povezavo oseba-sladica, če še ne obstaja."""

        with self.conn:
            with self.conn.cursor() as cur:
                cur.execute(
                    """
                    INSERT INTO priljubljeno (sladica, oseba)
                    VALUES (%s, %s)
                    ON CONFLICT (sladica, oseba) DO NOTHING
                    """,
                    (sladica_id, oseba_id),
                )

    def odstrani_iz_priljubljenih(
        self, oseba_id: int, sladica_id: int
    ) -> None:
        """Odstrani povezavo; ne izbriše niti osebe niti recepta."""

        with self.conn:
            with self.conn.cursor() as cur:
                cur.execute(
                    """
                    DELETE FROM priljubljeno
                    WHERE oseba = %s AND sladica = %s
                    """,
                    (oseba_id, sladica_id),
                )

    def je_priljubljena(self, oseba_id: int, sladica_id: int) -> bool:
        """Pove, ali ima oseba izbrano sladico med priljubljenimi."""

        with self.conn:
            with self.conn.cursor() as cur:
                cur.execute(
                    """
                    SELECT EXISTS (
                        SELECT 1
                        FROM priljubljeno
                        WHERE oseba = %s AND sladica = %s
                    )
                    """,
                    (oseba_id, sladica_id),
                )
                return cur.fetchone()[0]

    def dobi_priljubljene(self, oseba_id: int) -> list[SladicaDTO]:
        """Vrne vse priljubljene sladice izbrane osebe."""

        with self.conn:
            with self.conn.cursor() as cur:
                cur.execute(
                    self.SQL_SLADICE
                    + """
                    JOIN priljubljeno AS p ON p.sladica = s.id
                    WHERE p.oseba = %s
                    ORDER BY s.ime
                    """,
                    (oseba_id,),
                )
                vrstice = cur.fetchall()

        return [self._ustvari_sladico_dto(vrstica) for vrstica in vrstice]
