#!/bin/bash

export BOTTLE_PORT=8080
export BOTTLE_RELOADER=False
export BOTTLE_DEBUG=False
export BOTTLE_ROOT=${JUPYTERHUB_SERVICE_PREFIX}proxy/${BOTTLE_PORT}/

# izberemo vrata do katerih lahko dostopa mybinder
export DB_PORT=443

python app.py &
exec "$@"